[build]
builder = "Dockerfile"

[deploy]
startCommand = "npm run prisma:generate && npm run prisma:migrate -- --name init && npm start"
healthcheckPath = "/v1/health"
healthcheckTimeout = 300

[[services]]
name = "paygrade-backend"
env = { PORT = "3000", NODE_ENV = "production" }