import PDFDocument from 'pdfkit';

class PDFService {
  generateSalaryReport(data: any): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const buffers: Buffer[] = [];

      doc.on('data', (buffer) => buffers.push(buffer));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      // Header
      doc.fontSize(24).text('PayGrade Salary Intelligence Report', { align: 'center' });
      doc.moveDown();

      // Job Info
      doc.fontSize(16).text(`Job Role: ${data.role_detected}`);
      doc.fontSize(14).text(`Location: ${data.location}`);
      doc.fontSize(14).text(`Company: ${data.company || 'Unknown'}`);
      doc.moveDown();

      // Salary Range
      doc.fontSize(16).text('Salary Range');
      doc.fontSize(14).text(`Minimum: ${this.formatCurrency(data.range.min)}`);
      doc.fontSize(14).text(`25th Percentile: ${this.formatCurrency(data.range.p25)}`);
      doc.fontSize(14).text(`Median: ${this.formatCurrency(data.range.median)}`);
      doc.fontSize(14).text(`75th Percentile: ${this.formatCurrency(data.range.p75)}`);
      doc.fontSize(14).text(`Maximum: ${this.formatCurrency(data.range.max)}`);
      doc.moveDown();

      // Confidence and Data Points
      doc.fontSize(14).text(`Confidence: ${data.confidence}`);
      doc.fontSize(14).text(`Data Points: ${data.data_points}`);
      doc.moveDown();

      // Sources
      doc.fontSize(16).text('Data Sources');
      data.sources.forEach((source: any) => {
        doc.fontSize(12).text(`- ${source.source}: ${source.count} data points`);
      });
      doc.moveDown();

      // Salary Assessment
      if (data.posted_salary_assessment) {
        doc.fontSize(16).text('Posted Salary Assessment');
        doc.fontSize(14).text(`Posted: ${this.formatCurrency(data.posted_salary_assessment.posted)}`);
        doc.fontSize(14).text(`Comparison: ${data.posted_salary_assessment.label}`);
        doc.fontSize(14).text(`Difference: ${data.posted_salary_assessment.pct_diff}%`);
        doc.moveDown();
      }

      // Trends
      if (data.trends) {
        doc.fontSize(16).text('Salary Trends');
        doc.fontSize(14).text(`1 Year: ${data.trends.oneYear > 0 ? '+' : ''}${data.trends.oneYear}%`);
        doc.fontSize(14).text(`3 Years: ${data.trends.threeYear > 0 ? '+' : ''}${data.trends.threeYear}%`);
        doc.fontSize(14).text(`5 Years: ${data.trends.fiveYear > 0 ? '+' : ''}${data.trends.fiveYear}%`);
        doc.moveDown();
      }

      // Remote Adjustment
      if (data.remote_adjustment) {
        doc.fontSize(16).text('Remote Work Impact');
        doc.fontSize(14).text(`Remote Adjustment: ${data.remote_adjustment.remote_pct > 0 ? '+' : ''}${data.remote_adjustment.remote_pct}%`);
        doc.fontSize(14).text(`Remote Range: ${this.formatCurrency(data.remote_adjustment.adjusted_range.min)} - ${this.formatCurrency(data.remote_adjustment.adjusted_range.max)}`);
        doc.fontSize(14).text(`Remote Median: ${this.formatCurrency(data.remote_adjustment.adjusted_range.median)}`);
        doc.moveDown();
      }

      // Cost of Living
      if (data.cost_of_living) {
        doc.fontSize(16).text('Cost of Living');
        doc.fontSize(14).text(`Cost of Living Index: ${data.cost_of_living.index}`);
        doc.fontSize(14).text(`Comparison to National Average: ${data.cost_of_living.compared_to_national_avg > 0 ? '+' : ''}${data.cost_of_living.compared_to_national_avg}%`);
        doc.fontSize(14).text(`Salary Adjustment: ${data.cost_of_living.salary_adjustment > 0 ? '+' : ''}${data.cost_of_living.salary_adjustment}%`);
        doc.moveDown();
      }

      // Negotiation Insight
      if (data.negotiation_insight) {
        doc.fontSize(16).text('Negotiation Insight');
        doc.fontSize(12).text(data.negotiation_insight);
        doc.moveDown();
      }

      // Footer
      doc.fontSize(10).text('Generated by PayGrade - Salary Intelligence Tool', { align: 'center' });
      doc.fontSize(8).text('This report is for informational purposes only and should not be construed as professional advice.', { align: 'center' });

      doc.end();
    });
  }

  private formatCurrency(amount: number): string {
    return new Intl.NumberFormat('en-ZA', {
      style: 'currency',
      currency: 'ZAR',
      maximumFractionDigits: 0
    }).format(amount);
  }
}

export default new PDFService();
